### ISSUE TITLE
4.1 introduced breaking changes

### ISSUE THREAD

**Issue by Twipped** [salesforce/tough-cookie#246]
Our jest environment just started throwing errors because `allowSpecialUseDomain` is now being more enforced in this new release and `jest-environment-jsdom` doesn't set it. I tried to correct for it via Jest's `testEnvironmentOptions` config passthru, but that produced other problems. You may want to revert that release, it's gonna break a WHOLE LOT of builds.

**Comment by gbettencourt** [comment]
Also breaking our jest tests.  Don't see any breaking changes mentioned in the release notes.

**Comment by arpowers** [comment]
Same here! Happy that this isn't a bug on our end, was about to throw the computer out the window.

**Comment by arpowers** [comment]
@awaterma after reviewing a few things, this is definitely a breaking change and probably causing lots some headaches right now.  Recommend publishing a rollback minor release and pushing v5 with any updates.  For now, we are manually overriding the dep via PNPM as we can't update JSDom ourselves and there provide no easy way of patching this (e.g. to provide the options recommended in the error)...

**Comment by Jhzl2** [comment]
Our jest environment also failed in our tests. We work on a react app but we don't use tough-cookie. We assume that it is a dependency of some installed library. Could you give me a hand?
<img width="598" alt="image" src="https://user-images.githubusercontent.com/101297509/186033688-6d70ea65-dee4-417b-afa5-bd02ddc20cd9.png">

**Comment by awaterma** [comment]
I'm sorry this is causing you all some issues! For some background on how to use localhost as a special use domain, please see the discussion and tests in issue #215.

I believe this is coming up for v4.1.0 as @ShivanKaul implemented all of the "special-use" domains per RFC 6761 in the following p/r: https://github.com/salesforce/tough-cookie/pull/203/files, which we included in this release. We view this as continued work for the RFC that we started in v4.0.0.

In regards to working with cookies in `localhost` please see: https://www.rfc-editor.org/rfc/rfc6761.html#section-6.3

I will reach out to the team in Slack and see if we can get some discussion going. Sorry to cause issues for those that depend upon us; we are working to improve `tough-cookie` and keep up to date with the relevant RFCs to support cookies correctly into the future!

One direction we could go would be to set `rejectPublicSuffixes` to `false` in our default behavior to work around these issues for the `4.x.y` line.

@colincasey

**Comment by arpowers** [comment]
Most of us can certainly empathize with these type of challenges so no worries there. We appreciate the work on keeping things compliant. 

 End of the day, i think the best course of action is to move this to version 5; as a practice NPM versions should live and die with Semver since things are automatically updated and hard to override (using standard NPM client)...

**Comment by lyz810** [comment]
> Our jest environment just started throwing errors because `allowSpecialUseDomain` is now being more enforced in this new release and `jest-environment-jsdom` doesn't set it. I tried to correct for it via Jest's `testEnvironmentOptions` config passthru, but that produced other problems. You may want to revert that release, it's gonna break a WHOLE LOT of builds.

If you are using jest@28.x add 
```js
testEnvironmentOptions: {
   url: 'https://jestjs.io'
}
```
to jest config file
If you are using earlier version of jest, add
```js
testURL: 'https://jestjs.io'
```
to jest config file

You can change `https://jestjs.io` to your url
It works on me

https://jestjs.io/docs/upgrading-to-jest28#testurl

**Comment by privateOmega** [comment]
Broke my environment as well, Is there a simple fix for it, other than to pinpoint to the last version?

**Comment by MedAmineAyadi96** [comment]
Faced this problem this morning, quick walkaround is to add
`"tough-cookie": "4.0.0"`
to package.json file

**Comment by danymarques** [comment]
You can also add as a workaround in your pacakge.json :```  "overrides": {
    "jsdom": {
      "tough-cookie": "4.0.0"
    }
  },```

**Comment by antonvialibri1** [comment]
@lyz810 Adding a valid fully qualified domain name for `testEnvironmentOptions.url` worked for us.

**Comment by AbhaySBhosale** [comment]
New version introduced following error
`Cookie has domain set to the public suffix "localhost" which is a special use domain. To allow this, configure your CookieJar with {allowSpecialUseDomain:true, rejectPublicSuffixes: false}.`

**Comment by CSchulz** [comment]
Another workaround is setting your own CookieJar for the jsdom environment:

    testEnvironmentOptions: {
      url: 'http://localhost/',
      cookieJar: new toughCookie.CookieJar(undefined, {
        // first option copied from https://github.com/jsdom/jsdom/blob/master/lib/api.js
        // // jsdom cookie jars must be loose by default
        looseMode: true,
        allowSpecialUseDomain: true,
      }),
    },

**Comment by Twipped** [comment]
@CSchulz when I've tried that, I get an error that `this._cookieJar.getCookieStringSync` is not a function

**Comment by archer56** [comment]
I have raised a PR to fix the version of tough-cookie to v4.0.0 which should fix the immediate problem

https://github.com/jsdom/jsdom/pull/3420

**Comment by CSchulz** [comment]
> @CSchulz when I've tried that, I get an error that `this._cookieJar.getCookieStringSync` is not a function

Do you have a more detailled stacktrace?

**Comment by matthew-dean** [comment]
Ohhh THIS is why all our tests are breaking. 🤦‍♂️

**Comment by CSchulz** [comment]
Related #248

**Comment by privateOmega** [comment]
> overrides

This solution totally depends on which package-manager you are using, the overrides key is for npm v8+, for yarn, add it under resolutions and for older npm versions, add a npm-shrinkwrap.json file. or define resolutions and use something like https://www.npmjs.com/package/npm-force-resolutions.

**Comment by marcbrame** [comment]
The changes seem not to be on the version provided by npm. Have you updated the npm package release? @colincasey @awaterma. We still get the same error while running the tests.

**Comment by marcbrame** [comment]
For all working with **yarn**, you can overwrite the though-cookie version by adding this to your package.json:
```  
"resolutions": {
    "tough-cookie": "4.0.0"
}
```
Thanks to @privateOmega

**Comment by elmarbeckmann** [comment]
> I have raised a PR to fix the version of tough-cookie to v4.0.0 which should fix the immediate problem
> 
> [jsdom/jsdom#3420](https://github.com/jsdom/jsdom/pull/3420)

Hey @archer56 . This PR was closed and not merged because he (@domenic) is basically saying (and he is right) that you should revert this breaking change. Please do this because this is breaking A LOT of tests. Because it is a breaking change it should have been a major update of the tough-cookie package. 

For various reasons our dependency tree is complicated:
```
@my-repo
├─┬ @our-sub-dependency
│ └─┬ jest-preset-angular@11.1.2
│   └─┬ jest-environment-jsdom@27.5.1
│     └─┬ jsdom@16.7.0
│       └── tough-cookie@4.0.0  deduped
```
The temporary solutions posted above are difficult for us since we have lots of teams depending on our solutions. The real solution is fixing this issue in tough-cookie or reverting the changes since this is a breaking change. I hope you see the importance of this.

**Comment by awaterma** [comment]
We are currently reviewing a p/r that will resolve the issue; once merged we will roll out a new NPM release for tough-cookie to 4.1.1. 

Really appreciate everyone's patience as we do our best for tough-cookie and our customers!

**Comment by gauravshah27** [comment]
> We are currently reviewing a p/r that will resolve the issue; once merged we will roll out a new NPM release for tough-cookie to 4.1.1.
> 
> Really appreciate everyone's patience as we do our best for tough-cookie and our customers!

That sounds amazing. Thanks a lot for quick acknowledgement. This is affecting a lot of repositories right now and if you can release 4.1.1 that fixes it - that would be amazing.

**Comment by awaterma** [comment]
I'll reopen this until we get the 4.1.1 release completed.

**Comment by awaterma** [comment]
We've released 4.1.1 to NPM:

![Screen Shot 2022-08-24 at 12 39 06 PM](https://user-images.githubusercontent.com/65307/186508262-42f02783-70a2-445e-a754-6612ab803c7b.png)

**Comment by awaterma** [comment]
Closing this issue; I hope our latest release works well for everyone!

**Comment by puneetmakkar** [comment]
@awaterma tests are still failing for me at https://github.com/salesforce/tough-cookie/blob/master/lib/pubsuffix-psl.js#L62. 
I did a clean install. Am i doing something wrong ?
version: node v14.16.0 npm v6.14.1
npm ls tough-cookie:
├─┬ jest@26.6.0
│ └─┬ @jest/core@26.6.3
│   └─┬ jest-config@26.6.3
│     └─┬ jest-environment-jsdom@26.6.2
│       └─┬ jsdom@16.7.0
│         └── tough-cookie@4.1.1  deduped
├─┬ jsdom@15.1.1
│ ├─┬ request@2.88.2
│ │ └── tough-cookie@2.5.0 
│ ├─┬ request-promise-native@1.0.9
│ │ └── tough-cookie@2.5.0 
│ └── tough-cookie@3.0.1 
└── tough-cookie@4.1.1

**Comment by CSchulz** [comment]
> Hi @awaterma tests are still failing for me at https://github.com/salesforce/tough-cookie/blob/master/lib/pubsuffix-psl.js#L62. I did a clean install and also included tough-cookie@4.1.1 in package.json dev dependencies. version: node v14.16.0 npm v6.14.1 npm ls tough-cookie: ├─┬ jest@26.6.0 │ └─┬ @jest/core@26.6.3 │ └─┬ jest-config@26.6.3 │ └─┬ jest-environment-jsdom@26.6.2 │ └─┬ jsdom@16.7.0 │ └── tough-cookie@4.1.1 deduped ├─┬ jsdom@15.1.1 │ ├─┬ request@2.88.2 │ │ └── tough-cookie@2.5.0 │ ├─┬ request-promise-native@1.0.9 │ │ └── tough-cookie@2.5.0 │ └── tough-cookie@3.0.1 └── tough-cookie@4.1.1

Are you using localhost as your url? Then you have to change your url to localhost.local for more details see #248

**Comment by Ltchoc221** [comment]
I am also still seeing this issue using 4.1.1:
`  `-- jest@27.5.1
    `-- @jest/core@27.5.1
      `-- jest-config@27.5.1
        `-- jest-environment-jsdom@27.5.1
          `-- jsdom@16.7.0
            `-- tough-cookie@4.1.1`

Did the patch completely revert the change that caused this, or was there a new patch laid over the original change in an attempt to fix?

**Comment by Uninen** [comment]
4.1.1 doesn't solve the issue for Vitest users because (at least to my knowledge, please correct me if I'm wrong) there's no way to configure jsdom -- our tests are still failing. (The workaround is to override tough-cookie version to 4.0.0)

```
vitest 0.22.1
└─┬ jsdom 20.0.0 peer
  └── tough-cookie 4.1.1
```

**Comment by gauravshah27** [comment]
4.1.1 - this does not solve the issue.

**Comment by gbettencourt** [comment]
4.1.1 not working for me either

**Comment by LiuJinYang9527** [comment]
4.1.1 still not working

**Comment by dolevoper** [comment]
having the same issue with 4.1.1

**Comment by awaterma** [comment]
We have a new patch for this issue. We believe that we have now resolved a bug for how we treated single word special use domains (localhost and invalid) that should resolve this issue for everyone.

**Comment by gauravshah27** [comment]
@awaterma - I can confirm that 4.1.2 is working for us. Really appreciate the ownership on the issue and swiftness with which the patch was released. Thanks a lot.

**Comment by SevenOutman** [comment]
Also confirm 4.1.2 is working here. For users who had trouble with jsdom/jest, you can add `overrides` to your `package.json` and run `npm update tough-cookie` to bump it to the desired version.

```json
{
  "overrides": {
    "tough-cookie": "4.1.2"
  }
}
```

Reference: https://stackoverflow.com/a/64273186

**Comment by dolevoper** [comment]
Also here to confirm the new version works for us :)
Thank you!
